name: 更新插件API类型仓库

on:
  push:
    paths:
      - 'src/preload/generated/ipc-api-plugin.ts'

jobs:
  notify-plugin-api-types:
    runs-on: ubuntu-latest
    steps:
      - name: 触发plugin-api-types仓库工作流
        env:
          GITHUB_TOKEN: ${{ secrets.API_TYPES_TRIGGER_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/frontend-camp-25-12/plugin-api-types/dispatches \
            -d '{"event_type":"update-type-definitions"}'
