name: 更新plugin-pack的plugin.json zod定义

on:
  push:
    paths:
      - 'src/share/plugins/type.zod.d.ts'

jobs:
  notify-plugin-pack:
    runs-on: ubuntu-latest
    steps:
      - name: 触发plugin-pack仓库工作流
        env:
          GITHUB_TOKEN: ${{ secrets.API_TYPES_TRIGGER_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/frontend-camp-25-12/plugin-pack/dispatches \
            -d '{"event_type":"update-type-definitions"}'
